// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWuMkVw-fCOEnKcZ8uZJseK4oE7QSk1jw',
    appId: '1:613521780876:web:e5055fd5b64a25da0f8ba9',
    messagingSenderId: '613521780876',
    projectId: 'shiipou-firebase',
    authDomain: 'shiipou-firebase.firebaseapp.com',
    storageBucket: 'shiipou-firebase.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXD7iybuB-jIoJkuvD6JgUjSFHlbezKc0',
    appId: '1:613521780876:android:8eff174d6c93cb5c0f8ba9',
    messagingSenderId: '613521780876',
    projectId: 'shiipou-firebase',
    storageBucket: 'shiipou-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rfK3CXAlHdy4oIiXSeaN8IJVLt0OhxY',
    appId: '1:613521780876:ios:a28ee07976107c530f8ba9',
    messagingSenderId: '613521780876',
    projectId: 'shiipou-firebase',
    storageBucket: 'shiipou-firebase.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

}